language: node_js
node_js:
  - node
before_install:
  - export PATH="$(yarn global bin):$PATH"
  - yarn global add tachyons-cli
cache: yarn
script: yarn verify
deploy:
  - provider: npm
    api_key: $AUTHOR_NPM_TOKEN
    email: $AUTHOR_EMAIL
    skip_cleanup: true
    on:
      repo: eggheadio/tachyons-egghead
      tags: true
      branch: master
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: LnEL+23Jv8ts6tufKfvKoRT81c8xvEOd+ZvErqmgXPIb5HG525eudD8WaOsAF1XKxSq74JRRYp9y5jSC6/r3TDBDsRNV9sW4U/0/peLnSF/yzBII+W2JEUFe9RdLNrVSMxQRfvBesl3QlHRxOJ1Jhz4QYaPAodsTqDPUrUiW6QA=
